export const MIN_ORGANIZATION_RUN_PARTICIPANTS = 2;
export const MAX_ORGANIZATION_RUN_PARTICIPANTS = 6;
export const MIN_AUTOMATED_ORGANIZATION_RUN_PARTICIPANTS = 3;
export const MAX_AUTOMATED_ORGANIZATION_RUN_PARTICIPANTS = 3;
